[package]
name = "m1-ctrl"
version = "0.1.2"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
description = "Giant Magellan Telescope primary mirror control system"
repository = "https://github.com/rconan/m1-ctrl"
documentation = "https://docs.rs/m1-ctrl"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[dependencies]
bincode = { version = "1.3.3", optional = true }
dos_actors = { version = "4.1.0", package = "gmt_dos-actors", default-features = false }
fem = { version = "1.1.1", package = "gmt-fem", default-features = false, optional = true }
log = "0.4.17"
nalgebra = { version = "0.31.1", optional = true }
paste = "1.0.5"
simulink-binder = "^0.1.0"
thiserror = "1.0.36"

[features]
default = ["fem"]
nalgebra = ["dep:nalgebra", "bincode"]

[build-dependencies]
cc = "1.0.68"
