[package]
name = "m1-ctrl"
version = "0.1.1"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2018"
license = "MIT"
description = "Giant Magellan Telescope primary mirror control system"
repository = "https://github.com/rconan/m1-ctrl"
documentation = "https://docs.rs/m1-ctrl"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[dependencies]
dosio = {  version = "^0.1.3", default-features = false }
paste = "1.0.5"
seq-macro = "0.2.2"
simulink-binder = "^0.1.0"
simulink-rs = "^0.1.0"

[build-dependencies]
cc = "1.0.68"

[features]
default = ["dosio/default"]
dos-prqt = ["dosio/prqt"]

[package.metadata.docs.rs]
no-default-features = true
features = ["dos-prqt"]