[package]
name = "m1-ctrl"
version = "0.1.0"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dosio = { git = "https://github.com/rconan/dosio.git", branch = "ns-opm-im" }
paste = "1.0.5"
seq-macro = "0.2.2"
simulink-binder = { git = "https://github.com/rconan/simulink-binder.git", branch = "main" }
simulink-rs = { git = "https://github.com/rconan/simulink-rs.git", branch = "main" }

[build-dependencies]
cc = "1.0.68"
