[package]
name = "gmt_m1-ctrl"
version = "0.1.0"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2021"
license = "MIT"
description = "Giant Magellan Telescope primary mirror control system"
repository = "https://github.com/rconan/m1-ctrl"
documentation = "https://docs.rs/m1-ctrl"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[workspace]
members = ["hardpoints", "actuators", "actuators/center", "actuators/outer"]

[workspace.dependencies]
bindgen = "0.63.0"
cc = "1.0.68"
matio-rs = "1.1.2"
gmt_dos-actors = { version = "5.0.1", path = "../dos-actors", default-features = false }
dos-clients_io = { version = "1.0.0", package = "gmt_dos-clients_io", path = "../dos-actors/clients/io" }

[dependencies]
dos-clients_io.workspace = true
gmt_dos-actors = { workspace = true, default-features = false }
hardpoints-dynamics = { version = "0.1.0", path = "hardpoints", package = "gmt_m1-ctrl_hardpoints-dynamics" }
actuators = { version = "0.1.0", path = "actuators", package = "gmt_m1-ctrl_actuators" }
nalgebra = "0.31.0"
gmt-fem = { version = "1.1.1", path = "../fem" }

[dev-dependencies]
anyhow = "1.0.68"
matio-rs = { workspace = true, features = ["nalgebra"] }
tokio = { version = "1.24.2", features = ["test-util", "rt-multi-thread"] }
